apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: solace
  labels:
    instance: solace
spec:
  replicas: 1
  selector:
    matchLabels:
      instance: solace
  template:
    metadata:
      name: solace
      labels:
        instance: solace
    spec:
      containers:
        - name: solace
          image: solace/solace-pubsub-standard:9.1.0.201
          env:
            - name: username_admin_globalaccesslevel
              value: "admin"
            - name: username_admin_password
              value: "admin"
          ports:
            - containerPort: 8080
            - containerPort: 55555
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          readinessProbe:
            tcpSocket:
              port: 55555
            initialDelaySeconds: 300
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 55555
            initialDelaySeconds: 300
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
      initContainers:
        - name: solace-init
          image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
          command: ["/bin/sh"]
          args: ["-c", "sleep 60; until nc -v -z -w 3 postgres 5432; do echo 'Waiting for PostgresSQL ...'; sleep 3; done"]
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      terminationGracePeriodSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: solace
spec:
  selector:
    instance: solace
  ports:
    - name: admin
      port: 8080
      nodePort: 30080
    - name: messages
      port: 55555
      nodePort: 30555
  type: NodePort
