apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: teamcity-server
  labels:
    instance: teamcity-server
spec:
  replicas: 1
  selector:
    matchLabels:
      instance: teamcity-server
  template:
    metadata:
      name: teamcity-server
      labels:
        instance: teamcity-server
    spec:
      containers:
        - name: teamcity-server
          image: jetbrains/teamcity-server:2019.2.2
          env:
            - name: TEAMCITY_SERVER_MEM_OPTS
              value: "-Xmx4g"
          ports:
            - containerPort: 8111
          readinessProbe:
            tcpSocket:
              port: 8111
            initialDelaySeconds: 600
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 8111
            initialDelaySeconds: 600
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
            - name: data
              mountPath: /data/teamcity_server/datadir
              readOnly: false
            - name: data
              mountPath: /opt/teamcity/logs
              readOnly: false
      initContainers:
        - name: teamcity-server-init
          image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
          command: ["/bin/sh"]
          args: ["-c", "sleep 60; until nc -v -z -w 3 nexus 8081; do echo 'Waiting for Nexus ...'; sleep 3; done"]
      volumes:
        - name: data
          hostPath:
            path: "/opt/volumes/teamcity-server/data"
        - name: logs
          hostPath:
            path: "/opt/volumes/teamcity-server/logs"
---
apiVersion: v1
kind: Service
metadata:
  name: teamcity-server
spec:
  selector:
    instance: teamcity-server
  ports:
    - name: http
      port: 8111
      nodePort: 30111
  type: NodePort
