apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: artifactory
  labels:
    instance: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      instance: artifactory
  template:
    metadata:
      name: artifactory
      labels:
        instance: artifactory
    spec:
      containers:
        - name: artifactory
          image: releases-docker.jfrog.io/jfrog/artifactory-oss:6.23.15
          ports:
            - name: main
              containerPort: 8081
            - name: http
              containerPort: 8082
          volumeMounts:
            - name: data
              mountPath: /var/opt/jfrog/artifactory
              readOnly: false
      initContainers:
        - name: artifactory-init
          image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
          command: [ "/bin/sh" ]
          args:
            - -c
            - sleep 60;
      volumes:
        - name: data
          hostPath:
            path: "/opt/volumes/jfrog/artifactory/var"
      terminationGracePeriodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: artifactory
spec:
  selector:
    instance: artifactory
  ports:
    - name: main
      port: 8081
      nodePort: 30081
    - name: http
      port: 8082
      nodePort: 30082
  type: NodePort
