apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    tag: zookeeper
spec:
  containers:
    - name: zookeeper
      image: bitnami/zookeeper:3.5.7
      ports:
        - name: client
          containerPort: 2181
      env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: ZOO_PORT_NUMBER
          value: "2181"
        - name: ZOO_TICK_TIME
          value: "2000"
  restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    tag: zookeeper
  ports:
    - name: client
      port: 2181
      nodePort: 30181
  type: NodePort
